{
  "uid" : "2ddbafef8ae34cbd",
  "name" : "确认密码输入为空",
  "fullName" : "testcase.test_login.TestLogin#test_login01",
  "historyId" : "1ee099853c08e83b466b85648f89aead",
  "time" : {
    "start" : 1650511270265,
    "stop" : 1650511270265,
    "duration" : 0
  },
  "status" : "failed",
  "statusMessage" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:82: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
  "statusTrace" : "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase\\test_login.py:82: AssumptionFailure\nE               >>\tpytest.assume(flag == False)\nE               AssertionError: assert False\n\nD:\\Python\\lib\\site-packages\\six.py:718: FailedAssumption",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 8,
  "retriesStatusChange" : true,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:82: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
    "statusTrace" : "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               testcase\\test_login.py:82: AssumptionFailure\nE               >>\tpytest.assume(flag == False)\nE               AssertionError: assert False\n\nD:\\Python\\lib\\site-packages\\six.py:718: FailedAssumption",
    "steps" : [ {
      "name" : "预期与结果",
      "time" : {
        "start" : 1650511270281,
        "stop" : 1650511270281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "77b8a3376910d841",
        "name" : "预期",
        "source" : "77b8a3376910d841.json",
        "type" : "application/json",
        "size" : 49
      }, {
        "uid" : "a56477b3949526c7",
        "name" : "结果",
        "source" : "a56477b3949526c7.json",
        "type" : "application/json",
        "size" : 49
      } ],
      "parameters" : [ ],
      "attachmentsCount" : 2,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "响应失败原因",
      "time" : {
        "start" : 1650511270281,
        "stop" : 1650511270281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "6f3d4212e813dfa1",
        "name" : "数据",
        "source" : "6f3d4212e813dfa1.txt",
        "type" : "text/plain",
        "size" : 65
      } ],
      "parameters" : [ ],
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : true
    }, {
      "name" : "断言结果",
      "time" : {
        "start" : 1650511270281,
        "stop" : 1650511270281,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ {
      "uid" : "530dc9adbdc6c41f",
      "name" : "接口路径",
      "source" : "530dc9adbdc6c41f.attach",
      "type" : "text/plain",
      "size" : 42
    }, {
      "uid" : "8e8729acdabdfbae",
      "name" : "请求参数",
      "source" : "8e8729acdabdfbae.attach",
      "type" : "text/plain",
      "size" : 160
    }, {
      "uid" : "f04c3e87d0558391",
      "name" : "预期结果",
      "source" : "f04c3e87d0558391.attach",
      "type" : "text/plain",
      "size" : 49
    }, {
      "uid" : "d22afa99e72b3ec8",
      "name" : "响应状态",
      "source" : "d22afa99e72b3ec8.attach",
      "type" : "text/plain",
      "size" : 16
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 7,
    "shouldDisplayMessage" : true,
    "stepsCount" : 3,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "注册接口"
  }, {
    "name" : "parentSuite",
    "value" : "testcase"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "Mikey"
  }, {
    "name" : "thread",
    "value" : "8616-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "testcase.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "case",
    "value" : "{'case_id': 4, 'case_title': '确认密码输入为空', 'url': 'http://127.0.0.1:6666/business/regist_form', 'case_data': '{\"username\":\"admin01\",\"password\":\"admin\",\"re_password\":\"\",\"phone\":\"15736884464\",\"sex\":\"女\",\"birthday\":\"1995-04-03\",\"qq\":\"12345@qq.com\",\"email\":\"19999@163,com\"}', 'res': '{\"code\": 1005, \"msg\": \"重复密码不能为空\"}', 'app_name': '注册接口', 'demo': '啊啊'}"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "f13def45a5e9ac8e",
      "status" : "broken",
      "statusDetails" : "AttributeError: module 'allure' has no attribute 'environment'",
      "time" : {
        "start" : 1650511252506,
        "stop" : 1650511252506,
        "duration" : 0
      }
    }, {
      "uid" : "c75226021743e38b",
      "status" : "broken",
      "statusDetails" : "AttributeError: module 'allure' has no attribute 'environment'",
      "time" : {
        "start" : 1650510618511,
        "stop" : 1650510618511,
        "duration" : 0
      }
    }, {
      "uid" : "8354ef41a0bd01cc",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650510303940,
        "stop" : 1650510303940,
        "duration" : 0
      }
    }, {
      "uid" : "ad00530b3b1ee8bb",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650510266191,
        "stop" : 1650510266191,
        "duration" : 0
      }
    }, {
      "uid" : "e77dffeb66a1da3e",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650510194666,
        "stop" : 1650510194666,
        "duration" : 0
      }
    }, {
      "uid" : "a60dff37a62a919a",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650510123202,
        "stop" : 1650510123202,
        "duration" : 0
      }
    }, {
      "uid" : "633f85eb982ecfa8",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650510084452,
        "stop" : 1650510084452,
        "duration" : 0
      }
    }, {
      "uid" : "10d1900485098ef6",
      "status" : "failed",
      "statusDetails" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntestcase\\test_login.py:81: AssumptionFailure\n>>\tpytest.assume(flag == False)\nAssertionError: assert False",
      "time" : {
        "start" : 1650509990569,
        "stop" : 1650509990569,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "2ddbafef8ae34cbd.json",
  "parameterValues" : [ "{'case_id': 4, 'case_title': '确认密码输入为空', 'url': 'http://127.0.0.1:6666/business/regist_form', 'case_data': '{\"username\":\"admin01\",\"password\":\"admin\",\"re_password\":\"\",\"phone\":\"15736884464\",\"sex\":\"女\",\"birthday\":\"1995-04-03\",\"qq\":\"12345@qq.com\",\"email\":\"19999@163,com\"}', 'res': '{\"code\": 1005, \"msg\": \"重复密码不能为空\"}', 'app_name': '注册接口', 'demo': '啊啊'}" ]
}